// AUTO-GENERATED bundled fallback — a frozen MatchesResponse captured from /api so the
// mobile app opens instantly and survives a backend outage (degrades to this,
// never blank). Replaced by live data on the first successful fetch. Regenerate
// by re-capturing the /api response and re-running the sanitizer. Do not hand-edit.
import type { MatchesResponse } from "../api-shape";

export const SOCCER_SNAPSHOT: MatchesResponse = {
  "source": "snapshot",
  "syncedAt": "2026-07-05T23:03:01.986Z",
  "liveCount": 0,
  "total": 104,
  "matches": [
    {
      "n": 1,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "RSA",
        "name": "South Africa",
        "flag": "🇿🇦",
        "color": "#007749",
        "real": true,
        "grp": "A"
      },
      "venue": "Estadio Banorte",
      "city": "Mexico City",
      "country": "Mexico",
      "utc": "2026-06-11T19:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 2,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "KOR",
        "name": "Korea Republic",
        "flag": "🇰🇷",
        "color": "#cd2e3a",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "CZE",
        "name": "Czechia",
        "flag": "🇨🇿",
        "color": "#4a7fd1",
        "real": true,
        "grp": "A"
      },
      "venue": "Estadio Akron",
      "city": "Guadalajara",
      "country": "Mexico",
      "utc": "2026-06-12T02:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 3,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "BIH",
        "name": "Bosnia & Herz.",
        "flag": "🇧🇦",
        "color": "#3b6fd1",
        "real": true,
        "grp": "B"
      },
      "venue": "BMO Field",
      "city": "Toronto",
      "country": "Canada",
      "utc": "2026-06-12T19:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 4,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "real": true,
        "grp": "D"
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-13T01:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 4,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 5,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "HAI",
        "name": "Haiti",
        "flag": "🇭🇹",
        "color": "#3a64c8",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "SCO",
        "name": "Scotland",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "color": "#4a90d9",
        "real": true,
        "grp": "C"
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-14T01:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 6,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "AUS",
        "name": "Australia",
        "flag": "🇦🇺",
        "color": "#0a8f4e",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "TUR",
        "name": "Türkiye",
        "flag": "🇹🇷",
        "color": "#e30a17",
        "real": true,
        "grp": "D"
      },
      "venue": "BC Place",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-06-14T04:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 7,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "real": true,
        "grp": "C"
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-13T22:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 8,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "QAT",
        "name": "Qatar",
        "flag": "🇶🇦",
        "color": "#8d1b3d",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "real": true,
        "grp": "B"
      },
      "venue": "Levi's Stadium",
      "city": "San Francisco Bay",
      "country": "USA",
      "utc": "2026-06-13T19:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 9,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "GER",
        "name": "Germany",
        "flag": "🇩🇪",
        "color": "#9aa0a6",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "CUW",
        "name": "Curaçao",
        "flag": "🇨🇼",
        "color": "#1f6fd0",
        "real": true,
        "grp": "E"
      },
      "venue": "NRG Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-06-14T17:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 7,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 10,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "NED",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "color": "#ff6200",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "JPN",
        "name": "Japan",
        "flag": "🇯🇵",
        "color": "#bc002d",
        "real": true,
        "grp": "F"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-14T20:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 11,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "CIV",
        "name": "Côte d'Ivoire",
        "flag": "🇨🇮",
        "color": "#f77f00",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "ECU",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "color": "#f5d100",
        "real": true,
        "grp": "E"
      },
      "venue": "Lincoln Financial Field",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-06-14T23:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 12,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "SWE",
        "name": "Sweden",
        "flag": "🇸🇪",
        "color": "#4a90d9",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "TUN",
        "name": "Tunisia",
        "flag": "🇹🇳",
        "color": "#e70013",
        "real": true,
        "grp": "F"
      },
      "venue": "Estadio BBVA",
      "city": "Monterrey",
      "country": "Mexico",
      "utc": "2026-06-15T02:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 5,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 13,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "CPV",
        "name": "Cabo Verde",
        "flag": "🇨🇻",
        "color": "#3b6fd1",
        "real": true,
        "grp": "H"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-06-15T16:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 14,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "real": true,
        "grp": "G"
      },
      "venue": "Lumen Field",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-06-15T19:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 15,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "KSA",
        "name": "Saudi Arabia",
        "flag": "🇸🇦",
        "color": "#0a8f4e",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "URU",
        "name": "Uruguay",
        "flag": "🇺🇾",
        "color": "#5c9fd6",
        "real": true,
        "grp": "H"
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-06-15T22:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 16,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "IRN",
        "name": "Iran",
        "flag": "🇮🇷",
        "color": "#239f40",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "NZL",
        "name": "New Zealand",
        "flag": "🇳🇿",
        "color": "#b8bcc0",
        "real": true,
        "grp": "G"
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-16T01:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 17,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "SEN",
        "name": "Senegal",
        "flag": "🇸🇳",
        "color": "#1aa84a",
        "real": true,
        "grp": "I"
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-16T19:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 18,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "IRQ",
        "name": "Iraq",
        "flag": "🇮🇶",
        "color": "#cf2c3a",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "real": true,
        "grp": "I"
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-16T22:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 4,
      "minute": null,
      "pens": null
    },
    {
      "n": 19,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "ALG",
        "name": "Algeria",
        "flag": "🇩🇿",
        "color": "#0a8f4e",
        "real": true,
        "grp": "J"
      },
      "venue": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-06-17T01:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 20,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "AUT",
        "name": "Austria",
        "flag": "🇦🇹",
        "color": "#ed2939",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "JOR",
        "name": "Jordan",
        "flag": "🇯🇴",
        "color": "#3a8f5f",
        "real": true,
        "grp": "J"
      },
      "venue": "Levi's Stadium",
      "city": "San Francisco Bay",
      "country": "USA",
      "utc": "2026-06-17T04:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 21,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "COD",
        "name": "DR Congo",
        "flag": "🇨🇩",
        "color": "#2b8cff",
        "real": true,
        "grp": "K"
      },
      "venue": "NRG Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-06-17T17:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 22,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "CRO",
        "name": "Croatia",
        "flag": "🇭🇷",
        "color": "#d10000",
        "real": true,
        "grp": "L"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-17T20:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 4,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 23,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "GHA",
        "name": "Ghana",
        "flag": "🇬🇭",
        "color": "#0a8f4e",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "PAN",
        "name": "Panama",
        "flag": "🇵🇦",
        "color": "#c8102e",
        "real": true,
        "grp": "L"
      },
      "venue": "BMO Field",
      "city": "Toronto",
      "country": "Canada",
      "utc": "2026-06-17T23:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 24,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "UZB",
        "name": "Uzbekistan",
        "flag": "🇺🇿",
        "color": "#1eb53a",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "COL",
        "name": "Colombia",
        "flag": "🇨🇴",
        "color": "#fcd116",
        "real": true,
        "grp": "K"
      },
      "venue": "Estadio Banorte",
      "city": "Mexico City",
      "country": "Mexico",
      "utc": "2026-06-18T02:00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 25,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "CZE",
        "name": "Czechia",
        "flag": "🇨🇿",
        "color": "#4a7fd1",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "RSA",
        "name": "South Africa",
        "flag": "🇿🇦",
        "color": "#007749",
        "real": true,
        "grp": "A"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-06-18T16:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 26,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "BIH",
        "name": "Bosnia & Herz.",
        "flag": "🇧🇦",
        "color": "#3b6fd1",
        "real": true,
        "grp": "B"
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-18T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 4,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 27,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "QAT",
        "name": "Qatar",
        "flag": "🇶🇦",
        "color": "#8d1b3d",
        "real": true,
        "grp": "B"
      },
      "venue": "BC Place",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-06-18T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 6,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 28,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "KOR",
        "name": "Korea Republic",
        "flag": "🇰🇷",
        "color": "#cd2e3a",
        "real": true,
        "grp": "A"
      },
      "venue": "Estadio Akron",
      "city": "Guadalajara",
      "country": "Mexico",
      "utc": "2026-06-19T01:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 29,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "AUS",
        "name": "Australia",
        "flag": "🇦🇺",
        "color": "#0a8f4e",
        "real": true,
        "grp": "D"
      },
      "venue": "Lumen Field",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-06-19T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 30,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "SCO",
        "name": "Scotland",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "color": "#4a90d9",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "real": true,
        "grp": "C"
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-19T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 31,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "HAI",
        "name": "Haiti",
        "flag": "🇭🇹",
        "color": "#3a64c8",
        "real": true,
        "grp": "C"
      },
      "venue": "Lincoln Financial Field",
      "city": "San Francisco Bay",
      "country": "USA",
      "utc": "2026-06-20T00:30Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 32,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "TUR",
        "name": "Türkiye",
        "flag": "🇹🇷",
        "color": "#e30a17",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "real": true,
        "grp": "D"
      },
      "venue": "Levi's Stadium",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-06-20T03:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 33,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "NED",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "color": "#ff6200",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "SWE",
        "name": "Sweden",
        "flag": "🇸🇪",
        "color": "#4a90d9",
        "real": true,
        "grp": "F"
      },
      "venue": "NRG Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-20T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 5,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 34,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "GER",
        "name": "Germany",
        "flag": "🇩🇪",
        "color": "#9aa0a6",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "CIV",
        "name": "Côte d'Ivoire",
        "flag": "🇨🇮",
        "color": "#f77f00",
        "real": true,
        "grp": "E"
      },
      "venue": "BMO Field",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-06-20T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 35,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "ECU",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "color": "#f5d100",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "CUW",
        "name": "Curaçao",
        "flag": "🇨🇼",
        "color": "#1f6fd0",
        "real": true,
        "grp": "E"
      },
      "venue": "GEHA Field at Arrowhead Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-06-21T00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 36,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "TUN",
        "name": "Tunisia",
        "flag": "🇹🇳",
        "color": "#e70013",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "JPN",
        "name": "Japan",
        "flag": "🇯🇵",
        "color": "#bc002d",
        "real": true,
        "grp": "F"
      },
      "venue": "Estadio BBVA",
      "city": "Monterrey",
      "country": "Mexico",
      "utc": "2026-06-21T04:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 4,
      "minute": null,
      "pens": null
    },
    {
      "n": 37,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "KSA",
        "name": "Saudi Arabia",
        "flag": "🇸🇦",
        "color": "#0a8f4e",
        "real": true,
        "grp": "H"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-06-21T16:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 4,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 38,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "IRN",
        "name": "Iran",
        "flag": "🇮🇷",
        "color": "#239f40",
        "real": true,
        "grp": "G"
      },
      "venue": "SoFi Stadium",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-06-21T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 39,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "URU",
        "name": "Uruguay",
        "flag": "🇺🇾",
        "color": "#5c9fd6",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "CPV",
        "name": "Cabo Verde",
        "flag": "🇨🇻",
        "color": "#3b6fd1",
        "real": true,
        "grp": "H"
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-06-21T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 40,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "NZL",
        "name": "New Zealand",
        "flag": "🇳🇿",
        "color": "#b8bcc0",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "real": true,
        "grp": "G"
      },
      "venue": "BC Place",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-22T01:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 41,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "AUT",
        "name": "Austria",
        "flag": "🇦🇹",
        "color": "#ed2939",
        "real": true,
        "grp": "J"
      },
      "venue": "AT&T Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-06-22T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 42,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "IRQ",
        "name": "Iraq",
        "flag": "🇮🇶",
        "color": "#cf2c3a",
        "real": true,
        "grp": "I"
      },
      "venue": "Lincoln Financial Field",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-22T21:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 43,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "SEN",
        "name": "Senegal",
        "flag": "🇸🇳",
        "color": "#1aa84a",
        "real": true,
        "grp": "I"
      },
      "venue": "MetLife Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-23T00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 44,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "JOR",
        "name": "Jordan",
        "flag": "🇯🇴",
        "color": "#3a8f5f",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "ALG",
        "name": "Algeria",
        "flag": "🇩🇿",
        "color": "#0a8f4e",
        "real": true,
        "grp": "J"
      },
      "venue": "Levi's Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-23T03:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 45,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "UZB",
        "name": "Uzbekistan",
        "flag": "🇺🇿",
        "color": "#1eb53a",
        "real": true,
        "grp": "K"
      },
      "venue": "NRG Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-06-23T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 5,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 46,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "GHA",
        "name": "Ghana",
        "flag": "🇬🇭",
        "color": "#0a8f4e",
        "real": true,
        "grp": "L"
      },
      "venue": "Gillette Stadium",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-06-23T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 47,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "PAN",
        "name": "Panama",
        "flag": "🇵🇦",
        "color": "#c8102e",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "CRO",
        "name": "Croatia",
        "flag": "🇭🇷",
        "color": "#d10000",
        "real": true,
        "grp": "L"
      },
      "venue": "BMO Field",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-23T23:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 48,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "COL",
        "name": "Colombia",
        "flag": "🇨🇴",
        "color": "#fcd116",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "COD",
        "name": "DR Congo",
        "flag": "🇨🇩",
        "color": "#2b8cff",
        "real": true,
        "grp": "K"
      },
      "venue": "Estadio Akron",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-06-24T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 49,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "real": true,
        "grp": "B"
      },
      "venue": "BC Place",
      "city": "San Francisco Bay",
      "country": "USA",
      "utc": "2026-06-24T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 50,
      "stage": "Group B",
      "grp": "B",
      "home": {
        "code": "BIH",
        "name": "Bosnia & Herz.",
        "flag": "🇧🇦",
        "color": "#3b6fd1",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "QAT",
        "name": "Qatar",
        "flag": "🇶🇦",
        "color": "#8d1b3d",
        "real": true,
        "grp": "B"
      },
      "venue": "Lumen Field",
      "city": "Toronto",
      "country": "Canada",
      "utc": "2026-06-24T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 51,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "SCO",
        "name": "Scotland",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "color": "#4a90d9",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "real": true,
        "grp": "C"
      },
      "venue": "Hard Rock Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-24T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 52,
      "stage": "Group C",
      "grp": "C",
      "home": {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "HAI",
        "name": "Haiti",
        "flag": "🇭🇹",
        "color": "#3a64c8",
        "real": true,
        "grp": "C"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-06-24T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 4,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 53,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "CZE",
        "name": "Czechia",
        "flag": "🇨🇿",
        "color": "#4a7fd1",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "real": true,
        "grp": "A"
      },
      "venue": "Estadio Banorte",
      "city": "Mexico City",
      "country": "Mexico",
      "utc": "2026-06-25T01:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 54,
      "stage": "Group A",
      "grp": "A",
      "home": {
        "code": "RSA",
        "name": "South Africa",
        "flag": "🇿🇦",
        "color": "#007749",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "KOR",
        "name": "Korea Republic",
        "flag": "🇰🇷",
        "color": "#cd2e3a",
        "real": true,
        "grp": "A"
      },
      "venue": "Estadio BBVA",
      "city": "Monterrey",
      "country": "Mexico",
      "utc": "2026-06-25T01:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 55,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "ECU",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "color": "#f5d100",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "GER",
        "name": "Germany",
        "flag": "🇩🇪",
        "color": "#9aa0a6",
        "real": true,
        "grp": "E"
      },
      "venue": "MetLife Stadium",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-06-25T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 56,
      "stage": "Group E",
      "grp": "E",
      "home": {
        "code": "CUW",
        "name": "Curaçao",
        "flag": "🇨🇼",
        "color": "#1f6fd0",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "CIV",
        "name": "Côte d'Ivoire",
        "flag": "🇨🇮",
        "color": "#f77f00",
        "real": true,
        "grp": "E"
      },
      "venue": "Lincoln Financial Field",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-25T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 57,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "JPN",
        "name": "Japan",
        "flag": "🇯🇵",
        "color": "#bc002d",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "SWE",
        "name": "Sweden",
        "flag": "🇸🇪",
        "color": "#4a90d9",
        "real": true,
        "grp": "F"
      },
      "venue": "AT&T Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-06-25T23:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 58,
      "stage": "Group F",
      "grp": "F",
      "home": {
        "code": "TUN",
        "name": "Tunisia",
        "flag": "🇹🇳",
        "color": "#e70013",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "NED",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "color": "#ff6200",
        "real": true,
        "grp": "F"
      },
      "venue": "GEHA Field at Arrowhead Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-06-25T23:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 59,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "TUR",
        "name": "Türkiye",
        "flag": "🇹🇷",
        "color": "#e30a17",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "real": true,
        "grp": "D"
      },
      "venue": "SoFi Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-06-26T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 60,
      "stage": "Group D",
      "grp": "D",
      "home": {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "AUS",
        "name": "Australia",
        "flag": "🇦🇺",
        "color": "#0a8f4e",
        "real": true,
        "grp": "D"
      },
      "venue": "Levi's Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-26T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 61,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "real": true,
        "grp": "I"
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-26T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 4,
      "minute": null,
      "pens": null
    },
    {
      "n": 62,
      "stage": "Group I",
      "grp": "I",
      "home": {
        "code": "SEN",
        "name": "Senegal",
        "flag": "🇸🇳",
        "color": "#1aa84a",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "IRQ",
        "name": "Iraq",
        "flag": "🇮🇶",
        "color": "#cf2c3a",
        "real": true,
        "grp": "I"
      },
      "venue": "BMO Field",
      "city": "Toronto",
      "country": "Canada",
      "utc": "2026-06-26T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 5,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 63,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "CPV",
        "name": "Cabo Verde",
        "flag": "🇨🇻",
        "color": "#3b6fd1",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "KSA",
        "name": "Saudi Arabia",
        "flag": "🇸🇦",
        "color": "#0a8f4e",
        "real": true,
        "grp": "H"
      },
      "venue": "NRG Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-06-27T00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 64,
      "stage": "Group H",
      "grp": "H",
      "home": {
        "code": "URU",
        "name": "Uruguay",
        "flag": "🇺🇾",
        "color": "#5c9fd6",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "real": true,
        "grp": "H"
      },
      "venue": "Estadio Akron",
      "city": "Guadalajara",
      "country": "Mexico",
      "utc": "2026-06-27T00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 65,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "IRN",
        "name": "Iran",
        "flag": "🇮🇷",
        "color": "#239f40",
        "real": true,
        "grp": "G"
      },
      "venue": "Lumen Field",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-06-27T03:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 66,
      "stage": "Group G",
      "grp": "G",
      "home": {
        "code": "NZL",
        "name": "New Zealand",
        "flag": "🇳🇿",
        "color": "#b8bcc0",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "real": true,
        "grp": "G"
      },
      "venue": "BC Place",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-06-27T03:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 5,
      "minute": null,
      "pens": null
    },
    {
      "n": 67,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "PAN",
        "name": "Panama",
        "flag": "🇵🇦",
        "color": "#c8102e",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "real": true,
        "grp": "L"
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-27T21:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 68,
      "stage": "Group L",
      "grp": "L",
      "home": {
        "code": "CRO",
        "name": "Croatia",
        "flag": "🇭🇷",
        "color": "#d10000",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "GHA",
        "name": "Ghana",
        "flag": "🇬🇭",
        "color": "#0a8f4e",
        "real": true,
        "grp": "L"
      },
      "venue": "Lincoln Financial Field",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-06-27T21:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 69,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "COL",
        "name": "Colombia",
        "flag": "🇨🇴",
        "color": "#fcd116",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "real": true,
        "grp": "K"
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-06-27T23:30Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 70,
      "stage": "Group K",
      "grp": "K",
      "home": {
        "code": "COD",
        "name": "DR Congo",
        "flag": "🇨🇩",
        "color": "#2b8cff",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "UZB",
        "name": "Uzbekistan",
        "flag": "🇺🇿",
        "color": "#1eb53a",
        "real": true,
        "grp": "K"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-06-27T23:30Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 71,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "ALG",
        "name": "Algeria",
        "flag": "🇩🇿",
        "color": "#0a8f4e",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "AUT",
        "name": "Austria",
        "flag": "🇦🇹",
        "color": "#ed2939",
        "real": true,
        "grp": "J"
      },
      "venue": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-06-28T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 72,
      "stage": "Group J",
      "grp": "J",
      "home": {
        "code": "JOR",
        "name": "Jordan",
        "flag": "🇯🇴",
        "color": "#3a8f5f",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "real": true,
        "grp": "J"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-28T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 73,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "RSA",
        "name": "South Africa",
        "flag": "🇿🇦",
        "color": "#007749",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "real": true,
        "grp": "B"
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-06-28T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 74,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "JPN",
        "name": "Japan",
        "flag": "🇯🇵",
        "color": "#bc002d",
        "real": true,
        "grp": "F"
      },
      "venue": "NRG Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-06-29T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 75,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "GER",
        "name": "Germany",
        "flag": "🇩🇪",
        "color": "#9aa0a6",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "real": true,
        "grp": "D"
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-06-29T20:30Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": {
        "away": 4,
        "home": 3
      }
    },
    {
      "n": 76,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "NED",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "color": "#ff6200",
        "real": true,
        "grp": "F"
      },
      "away": {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "real": true,
        "grp": "C"
      },
      "venue": "Estadio BBVA",
      "city": "Monterrey",
      "country": "Mexico",
      "utc": "2026-06-30T01:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": {
        "away": 3,
        "home": 2
      }
    },
    {
      "n": 77,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "real": true,
        "grp": "I"
      },
      "away": {
        "code": "SWE",
        "name": "Sweden",
        "flag": "🇸🇪",
        "color": "#4a90d9",
        "real": true,
        "grp": "F"
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-06-30T21:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 78,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "CIV",
        "name": "Côte d'Ivoire",
        "flag": "🇨🇮",
        "color": "#f77f00",
        "real": true,
        "grp": "E"
      },
      "away": {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "real": true,
        "grp": "I"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-06-30T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 79,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "ECU",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "color": "#f5d100",
        "real": true,
        "grp": "E"
      },
      "venue": "Estadio Banorte",
      "city": "Mexico City",
      "country": "Mexico",
      "utc": "2026-07-01T02:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 80,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "real": true,
        "grp": "L"
      },
      "away": {
        "code": "COD",
        "name": "DR Congo",
        "flag": "🇨🇩",
        "color": "#2b8cff",
        "real": true,
        "grp": "K"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-07-01T16:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 81,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "BIH",
        "name": "Bosnia & Herz.",
        "flag": "🇧🇦",
        "color": "#3b6fd1",
        "real": true,
        "grp": "B"
      },
      "venue": "Levi's Stadium",
      "city": "San Francisco Bay",
      "country": "USA",
      "utc": "2026-07-02T00:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 82,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "real": true,
        "grp": "G"
      },
      "away": {
        "code": "SEN",
        "name": "Senegal",
        "flag": "🇸🇳",
        "color": "#1aa84a",
        "real": true,
        "grp": "I"
      },
      "venue": "Lumen Field",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-07-01T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 83,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "CRO",
        "name": "Croatia",
        "flag": "🇭🇷",
        "color": "#d10000",
        "real": true,
        "grp": "L"
      },
      "venue": "BMO Field",
      "city": "Toronto",
      "country": "Canada",
      "utc": "2026-07-02T23:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 84,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "real": true,
        "grp": "H"
      },
      "away": {
        "code": "AUT",
        "name": "Austria",
        "flag": "🇦🇹",
        "color": "#ed2939",
        "real": true,
        "grp": "J"
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-07-02T19:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 85,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "ALG",
        "name": "Algeria",
        "flag": "🇩🇿",
        "color": "#0a8f4e",
        "real": true,
        "grp": "J"
      },
      "venue": "BC Place",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-07-03T03:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 2,
      "awayScore": 0,
      "minute": null,
      "pens": null
    },
    {
      "n": 86,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "CPV",
        "name": "Cabo Verde",
        "flag": "🇨🇻",
        "color": "#3b6fd1",
        "real": true,
        "grp": "H"
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-07-03T22:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 3,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 87,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "1K",
        "name": "Winner Group K",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "3rd D/E/I/J/L",
        "name": "3rd place · D/E/I/J/L",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Arrowhead Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-07-03T23:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 88,
      "stage": "R32",
      "grp": null,
      "home": {
        "code": "AUS",
        "name": "Australia",
        "flag": "🇦🇺",
        "color": "#0a8f4e",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "real": true,
        "grp": "G"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-07-03T18:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 1,
      "minute": null,
      "pens": {
        "away": 4,
        "home": 2
      }
    },
    {
      "n": 89,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "real": true,
        "grp": "I"
      },
      "venue": "Lincoln Financial Field",
      "city": "Philadelphia",
      "country": "USA",
      "utc": "2026-07-04T21:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 1,
      "minute": null,
      "pens": null
    },
    {
      "n": 90,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "real": true,
        "grp": "C"
      },
      "venue": "NRG Stadium",
      "city": "Houston",
      "country": "USA",
      "utc": "2026-07-04T17:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 0,
      "awayScore": 3,
      "minute": null,
      "pens": null
    },
    {
      "n": 91,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "real": true,
        "grp": "C"
      },
      "away": {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "real": true,
        "grp": "I"
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-07-05T20:00Z",
      "approx": false,
      "status": "ft",
      "homeScore": 1,
      "awayScore": 2,
      "minute": null,
      "pens": null
    },
    {
      "n": 92,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "real": true,
        "grp": "A"
      },
      "away": {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "real": true,
        "grp": "L"
      },
      "venue": "Estadio Banorte",
      "city": "Mexico City",
      "country": "Mexico",
      "utc": "2026-07-06T00:00Z",
      "approx": false,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 93,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "real": true,
        "grp": "K"
      },
      "away": {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "real": true,
        "grp": "H"
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-07-06T19:00Z",
      "approx": false,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 94,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "real": true,
        "grp": "D"
      },
      "away": {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "real": true,
        "grp": "G"
      },
      "venue": "Lumen Field",
      "city": "Seattle",
      "country": "USA",
      "utc": "2026-07-07T00:00Z",
      "approx": false,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 95,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "real": true,
        "grp": "J"
      },
      "away": {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "real": true,
        "grp": "G"
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-07-07T16:00Z",
      "approx": false,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 96,
      "stage": "R16",
      "grp": null,
      "home": {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "real": true,
        "grp": "B"
      },
      "away": {
        "code": "COL",
        "name": "Colombia",
        "flag": "🇨🇴",
        "color": "#fcd116",
        "real": true,
        "grp": "K"
      },
      "venue": "BC Place",
      "city": "Vancouver",
      "country": "Canada",
      "utc": "2026-07-07T20:00Z",
      "approx": false,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 97,
      "stage": "QF",
      "grp": null,
      "home": {
        "code": "W89",
        "name": "Winner · Match 89",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W90",
        "name": "Winner · Match 90",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Gillette Stadium",
      "city": "Boston",
      "country": "USA",
      "utc": "2026-07-09T21:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 98,
      "stage": "QF",
      "grp": null,
      "home": {
        "code": "W93",
        "name": "Winner · Match 93",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W94",
        "name": "Winner · Match 94",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "SoFi Stadium",
      "city": "Los Angeles",
      "country": "USA",
      "utc": "2026-07-11T00:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 99,
      "stage": "QF",
      "grp": null,
      "home": {
        "code": "W91",
        "name": "Winner · Match 91",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W92",
        "name": "Winner · Match 92",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-07-11T16:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 100,
      "stage": "QF",
      "grp": null,
      "home": {
        "code": "W95",
        "name": "Winner · Match 95",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W96",
        "name": "Winner · Match 96",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Arrowhead Stadium",
      "city": "Kansas City",
      "country": "USA",
      "utc": "2026-07-11T20:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 101,
      "stage": "SF",
      "grp": null,
      "home": {
        "code": "W97",
        "name": "Winner · Match 97",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W98",
        "name": "Winner · Match 98",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "AT&T Stadium",
      "city": "Dallas",
      "country": "USA",
      "utc": "2026-07-14T23:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 102,
      "stage": "SF",
      "grp": null,
      "home": {
        "code": "W99",
        "name": "Winner · Match 99",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W100",
        "name": "Winner · Match 100",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "country": "USA",
      "utc": "2026-07-15T19:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 103,
      "stage": "3rd Place",
      "grp": null,
      "home": {
        "code": "L101",
        "name": "Loser · Match 101",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "L102",
        "name": "Loser · Match 102",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "Hard Rock Stadium",
      "city": "Miami",
      "country": "USA",
      "utc": "2026-07-18T19:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    },
    {
      "n": 104,
      "stage": "Final",
      "grp": null,
      "home": {
        "code": "W101",
        "name": "Winner · Match 101",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "away": {
        "code": "W102",
        "name": "Winner · Match 102",
        "flag": "",
        "color": "#5b6b60",
        "real": false,
        "grp": null
      },
      "venue": "MetLife Stadium",
      "city": "New York/New Jersey",
      "country": "USA",
      "utc": "2026-07-19T19:00:00Z",
      "approx": true,
      "status": "sched",
      "homeScore": null,
      "awayScore": null,
      "minute": null,
      "pens": null
    }
  ]
};
