// AUTO-GENERATED bundled fallback — frozen /api/soccer/standings so the World Cup
// group tables render instantly and survive a backend outage. Replaced by live
// data on first fetch. Regenerate by re-capturing + re-running. Do not hand-edit.
import type { StandingsResponse } from "../api-shape";

export const SOCCER_STANDINGS_SNAPSHOT: StandingsResponse = {
  "source": "snapshot",
  "syncedAt": "2026-07-06T01:10:41.805Z",
  "groups": {
    "A": [
      {
        "code": "MEX",
        "name": "Mexico",
        "flag": "🇲🇽",
        "color": "#0a8f4e",
        "P": 3,
        "W": 3,
        "D": 0,
        "L": 0,
        "GF": 6,
        "GA": 0,
        "GD": 6,
        "Pts": 9
      },
      {
        "code": "RSA",
        "name": "South Africa",
        "flag": "🇿🇦",
        "color": "#007749",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 2,
        "GA": 3,
        "GD": -1,
        "Pts": 4
      },
      {
        "code": "KOR",
        "name": "Korea Republic",
        "flag": "🇰🇷",
        "color": "#cd2e3a",
        "P": 3,
        "W": 1,
        "D": 0,
        "L": 2,
        "GF": 2,
        "GA": 3,
        "GD": -1,
        "Pts": 3
      },
      {
        "code": "CZE",
        "name": "Czechia",
        "flag": "🇨🇿",
        "color": "#4a7fd1",
        "P": 3,
        "W": 0,
        "D": 1,
        "L": 2,
        "GF": 2,
        "GA": 6,
        "GD": -4,
        "Pts": 1
      }
    ],
    "B": [
      {
        "code": "SUI",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "color": "#d52b1e",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 7,
        "GA": 3,
        "GD": 4,
        "Pts": 7
      },
      {
        "code": "CAN",
        "name": "Canada",
        "flag": "🇨🇦",
        "color": "#e8473f",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 8,
        "GA": 3,
        "GD": 5,
        "Pts": 4
      },
      {
        "code": "BIH",
        "name": "Bosnia & Herz.",
        "flag": "🇧🇦",
        "color": "#3b6fd1",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 5,
        "GA": 6,
        "GD": -1,
        "Pts": 4
      },
      {
        "code": "QAT",
        "name": "Qatar",
        "flag": "🇶🇦",
        "color": "#8d1b3d",
        "P": 3,
        "W": 0,
        "D": 1,
        "L": 2,
        "GF": 2,
        "GA": 10,
        "GD": -8,
        "Pts": 1
      }
    ],
    "C": [
      {
        "code": "BRA",
        "name": "Brazil",
        "flag": "🇧🇷",
        "color": "#f5d100",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 7,
        "GA": 1,
        "GD": 6,
        "Pts": 7
      },
      {
        "code": "MAR",
        "name": "Morocco",
        "flag": "🇲🇦",
        "color": "#c1272d",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 6,
        "GA": 3,
        "GD": 3,
        "Pts": 7
      },
      {
        "code": "SCO",
        "name": "Scotland",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "color": "#4a90d9",
        "P": 3,
        "W": 1,
        "D": 0,
        "L": 2,
        "GF": 1,
        "GA": 4,
        "GD": -3,
        "Pts": 3
      },
      {
        "code": "HAI",
        "name": "Haiti",
        "flag": "🇭🇹",
        "color": "#3a64c8",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 2,
        "GA": 8,
        "GD": -6,
        "Pts": 0
      }
    ],
    "D": [
      {
        "code": "USA",
        "name": "USA",
        "flag": "🇺🇸",
        "color": "#2b5cc4",
        "P": 3,
        "W": 2,
        "D": 0,
        "L": 1,
        "GF": 8,
        "GA": 4,
        "GD": 4,
        "Pts": 6
      },
      {
        "code": "AUS",
        "name": "Australia",
        "flag": "🇦🇺",
        "color": "#0a8f4e",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 2,
        "GA": 2,
        "GD": 0,
        "Pts": 4
      },
      {
        "code": "PAR",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "color": "#d52b1e",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 2,
        "GA": 4,
        "GD": -2,
        "Pts": 4
      },
      {
        "code": "TUR",
        "name": "Türkiye",
        "flag": "🇹🇷",
        "color": "#e30a17",
        "P": 3,
        "W": 1,
        "D": 0,
        "L": 2,
        "GF": 3,
        "GA": 5,
        "GD": -2,
        "Pts": 3
      }
    ],
    "E": [
      {
        "code": "GER",
        "name": "Germany",
        "flag": "🇩🇪",
        "color": "#9aa0a6",
        "P": 3,
        "W": 2,
        "D": 0,
        "L": 1,
        "GF": 10,
        "GA": 4,
        "GD": 6,
        "Pts": 6
      },
      {
        "code": "CIV",
        "name": "Côte d'Ivoire",
        "flag": "🇨🇮",
        "color": "#f77f00",
        "P": 3,
        "W": 2,
        "D": 0,
        "L": 1,
        "GF": 4,
        "GA": 2,
        "GD": 2,
        "Pts": 6
      },
      {
        "code": "ECU",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "color": "#f5d100",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 2,
        "GA": 2,
        "GD": 0,
        "Pts": 4
      },
      {
        "code": "CUW",
        "name": "Curaçao",
        "flag": "🇨🇼",
        "color": "#1f6fd0",
        "P": 3,
        "W": 0,
        "D": 1,
        "L": 2,
        "GF": 1,
        "GA": 9,
        "GD": -8,
        "Pts": 1
      }
    ],
    "F": [
      {
        "code": "NED",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "color": "#ff6200",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 10,
        "GA": 4,
        "GD": 6,
        "Pts": 7
      },
      {
        "code": "JPN",
        "name": "Japan",
        "flag": "🇯🇵",
        "color": "#bc002d",
        "P": 3,
        "W": 1,
        "D": 2,
        "L": 0,
        "GF": 7,
        "GA": 3,
        "GD": 4,
        "Pts": 5
      },
      {
        "code": "SWE",
        "name": "Sweden",
        "flag": "🇸🇪",
        "color": "#4a90d9",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 7,
        "GA": 7,
        "GD": 0,
        "Pts": 4
      },
      {
        "code": "TUN",
        "name": "Tunisia",
        "flag": "🇹🇳",
        "color": "#e70013",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 2,
        "GA": 12,
        "GD": -10,
        "Pts": 0
      }
    ],
    "G": [
      {
        "code": "BEL",
        "name": "Belgium",
        "flag": "🇧🇪",
        "color": "#e8b800",
        "P": 3,
        "W": 1,
        "D": 2,
        "L": 0,
        "GF": 6,
        "GA": 2,
        "GD": 4,
        "Pts": 5
      },
      {
        "code": "EGY",
        "name": "Egypt",
        "flag": "🇪🇬",
        "color": "#c8102e",
        "P": 3,
        "W": 1,
        "D": 2,
        "L": 0,
        "GF": 5,
        "GA": 3,
        "GD": 2,
        "Pts": 5
      },
      {
        "code": "IRN",
        "name": "Iran",
        "flag": "🇮🇷",
        "color": "#239f40",
        "P": 3,
        "W": 0,
        "D": 3,
        "L": 0,
        "GF": 3,
        "GA": 3,
        "GD": 0,
        "Pts": 3
      },
      {
        "code": "NZL",
        "name": "New Zealand",
        "flag": "🇳🇿",
        "color": "#b8bcc0",
        "P": 3,
        "W": 0,
        "D": 1,
        "L": 2,
        "GF": 4,
        "GA": 10,
        "GD": -6,
        "Pts": 1
      }
    ],
    "H": [
      {
        "code": "ESP",
        "name": "Spain",
        "flag": "🇪🇸",
        "color": "#c60b1e",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 5,
        "GA": 0,
        "GD": 5,
        "Pts": 7
      },
      {
        "code": "CPV",
        "name": "Cabo Verde",
        "flag": "🇨🇻",
        "color": "#3b6fd1",
        "P": 3,
        "W": 0,
        "D": 3,
        "L": 0,
        "GF": 2,
        "GA": 2,
        "GD": 0,
        "Pts": 3
      },
      {
        "code": "URU",
        "name": "Uruguay",
        "flag": "🇺🇾",
        "color": "#5c9fd6",
        "P": 3,
        "W": 0,
        "D": 2,
        "L": 1,
        "GF": 3,
        "GA": 4,
        "GD": -1,
        "Pts": 2
      },
      {
        "code": "KSA",
        "name": "Saudi Arabia",
        "flag": "🇸🇦",
        "color": "#0a8f4e",
        "P": 3,
        "W": 0,
        "D": 2,
        "L": 1,
        "GF": 1,
        "GA": 5,
        "GD": -4,
        "Pts": 2
      }
    ],
    "I": [
      {
        "code": "FRA",
        "name": "France",
        "flag": "🇫🇷",
        "color": "#2b5cc4",
        "P": 3,
        "W": 3,
        "D": 0,
        "L": 0,
        "GF": 10,
        "GA": 2,
        "GD": 8,
        "Pts": 9
      },
      {
        "code": "NOR",
        "name": "Norway",
        "flag": "🇳🇴",
        "color": "#ba0c2f",
        "P": 3,
        "W": 2,
        "D": 0,
        "L": 1,
        "GF": 8,
        "GA": 7,
        "GD": 1,
        "Pts": 6
      },
      {
        "code": "SEN",
        "name": "Senegal",
        "flag": "🇸🇳",
        "color": "#1aa84a",
        "P": 3,
        "W": 1,
        "D": 0,
        "L": 2,
        "GF": 8,
        "GA": 6,
        "GD": 2,
        "Pts": 3
      },
      {
        "code": "IRQ",
        "name": "Iraq",
        "flag": "🇮🇶",
        "color": "#cf2c3a",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 1,
        "GA": 12,
        "GD": -11,
        "Pts": 0
      }
    ],
    "J": [
      {
        "code": "ARG",
        "name": "Argentina",
        "flag": "🇦🇷",
        "color": "#6cace4",
        "P": 3,
        "W": 3,
        "D": 0,
        "L": 0,
        "GF": 8,
        "GA": 1,
        "GD": 7,
        "Pts": 9
      },
      {
        "code": "AUT",
        "name": "Austria",
        "flag": "🇦🇹",
        "color": "#ed2939",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 6,
        "GA": 6,
        "GD": 0,
        "Pts": 4
      },
      {
        "code": "ALG",
        "name": "Algeria",
        "flag": "🇩🇿",
        "color": "#0a8f4e",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 5,
        "GA": 7,
        "GD": -2,
        "Pts": 4
      },
      {
        "code": "JOR",
        "name": "Jordan",
        "flag": "🇯🇴",
        "color": "#3a8f5f",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 3,
        "GA": 8,
        "GD": -5,
        "Pts": 0
      }
    ],
    "K": [
      {
        "code": "COL",
        "name": "Colombia",
        "flag": "🇨🇴",
        "color": "#fcd116",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 4,
        "GA": 1,
        "GD": 3,
        "Pts": 7
      },
      {
        "code": "POR",
        "name": "Portugal",
        "flag": "🇵🇹",
        "color": "#1aa84a",
        "P": 3,
        "W": 1,
        "D": 2,
        "L": 0,
        "GF": 6,
        "GA": 1,
        "GD": 5,
        "Pts": 5
      },
      {
        "code": "COD",
        "name": "DR Congo",
        "flag": "🇨🇩",
        "color": "#2b8cff",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 4,
        "GA": 3,
        "GD": 1,
        "Pts": 4
      },
      {
        "code": "UZB",
        "name": "Uzbekistan",
        "flag": "🇺🇿",
        "color": "#1eb53a",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 2,
        "GA": 11,
        "GD": -9,
        "Pts": 0
      }
    ],
    "L": [
      {
        "code": "ENG",
        "name": "England",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "color": "#cdd2d8",
        "P": 3,
        "W": 2,
        "D": 1,
        "L": 0,
        "GF": 6,
        "GA": 2,
        "GD": 4,
        "Pts": 7
      },
      {
        "code": "CRO",
        "name": "Croatia",
        "flag": "🇭🇷",
        "color": "#d10000",
        "P": 3,
        "W": 2,
        "D": 0,
        "L": 1,
        "GF": 5,
        "GA": 5,
        "GD": 0,
        "Pts": 6
      },
      {
        "code": "GHA",
        "name": "Ghana",
        "flag": "🇬🇭",
        "color": "#0a8f4e",
        "P": 3,
        "W": 1,
        "D": 1,
        "L": 1,
        "GF": 2,
        "GA": 2,
        "GD": 0,
        "Pts": 4
      },
      {
        "code": "PAN",
        "name": "Panama",
        "flag": "🇵🇦",
        "color": "#c8102e",
        "P": 3,
        "W": 0,
        "D": 0,
        "L": 3,
        "GF": 0,
        "GA": 4,
        "GD": -4,
        "Pts": 0
      }
    ]
  },
  "bestThirds": [
    "COD",
    "SWE",
    "ECU",
    "GHA",
    "BIH",
    "ALG",
    "PAR",
    "SEN"
  ]
};
