// Real static World Cup squads (start set). One clearly-commented dataset behind
// the team seam (teamData.ts). Each player: real name, position (GK/DEF/MID/FWD),
// shirt number, and isCaptain / isGoalkeeper flags. Teams not listed here fall
// back to a clearly-generic placeholder squad in teamData.ts.
//
// BACKEND SEAM: replace with Supabase (live rosters). Ages/stats stay derived
// placeholders in the seam — these are the real identities to anchor them to.
export type Pos = "GK" | "DEF" | "MID" | "FWD";
export type RosterPlayer = { name: string; pos: Pos; number: number; isCaptain?: boolean; isGoalkeeper?: boolean };

export const REAL_SQUADS: Record<string, RosterPlayer[]> = {
  ARG: [
    { name: "E. Martínez", pos: "GK", number: 23, isGoalkeeper: true },
    { name: "G. Rulli", pos: "GK", number: 12, isGoalkeeper: true },
    { name: "N. Molina", pos: "DEF", number: 26 },
    { name: "C. Romero", pos: "DEF", number: 13 },
    { name: "L. Martínez", pos: "DEF", number: 25 },
    { name: "N. Otamendi", pos: "DEF", number: 19 },
    { name: "N. Tagliafico", pos: "DEF", number: 3 },
    { name: "R. De Paul", pos: "MID", number: 7 },
    { name: "E. Fernández", pos: "MID", number: 24 },
    { name: "A. Mac Allister", pos: "MID", number: 20 },
    { name: "G. Lo Celso", pos: "MID", number: 18 },
    { name: "L. Messi", pos: "FWD", number: 10, isCaptain: true },
    { name: "J. Álvarez", pos: "FWD", number: 9 },
    { name: "Á. Di María", pos: "FWD", number: 11 },
    { name: "Lautaro Martínez", pos: "FWD", number: 22 },
    { name: "N. González", pos: "FWD", number: 21 },
  ],
  BRA: [
    { name: "Alisson", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "Bento", pos: "GK", number: 12, isGoalkeeper: true },
    { name: "Danilo", pos: "DEF", number: 2 },
    { name: "Marquinhos", pos: "DEF", number: 4, isCaptain: true },
    { name: "G. Magalhães", pos: "DEF", number: 14 },
    { name: "É. Militão", pos: "DEF", number: 3 },
    { name: "Wendell", pos: "DEF", number: 6 },
    { name: "Casemiro", pos: "MID", number: 5 },
    { name: "Bruno Guimarães", pos: "MID", number: 8 },
    { name: "Lucas Paquetá", pos: "MID", number: 10 },
    { name: "João Gomes", pos: "MID", number: 15 },
    { name: "Vinícius Jr", pos: "FWD", number: 7 },
    { name: "Rodrygo", pos: "FWD", number: 11 },
    { name: "Raphinha", pos: "FWD", number: 19 },
    { name: "Endrick", pos: "FWD", number: 9 },
    { name: "Savinho", pos: "FWD", number: 20 },
  ],
  FRA: [
    { name: "M. Maignan", pos: "GK", number: 16, isGoalkeeper: true },
    { name: "B. Samba", pos: "GK", number: 23, isGoalkeeper: true },
    { name: "J. Koundé", pos: "DEF", number: 5 },
    { name: "D. Upamecano", pos: "DEF", number: 4 },
    { name: "W. Saliba", pos: "DEF", number: 17 },
    { name: "T. Hernández", pos: "DEF", number: 22 },
    { name: "I. Konaté", pos: "DEF", number: 15 },
    { name: "A. Tchouaméni", pos: "MID", number: 8 },
    { name: "E. Camavinga", pos: "MID", number: 6 },
    { name: "A. Rabiot", pos: "MID", number: 14 },
    { name: "W. Zaïre-Emery", pos: "MID", number: 18 },
    { name: "K. Mbappé", pos: "FWD", number: 10, isCaptain: true },
    { name: "O. Dembélé", pos: "FWD", number: 11 },
    { name: "M. Thuram", pos: "FWD", number: 9 },
    { name: "R. Kolo Muani", pos: "FWD", number: 12 },
    { name: "B. Barcola", pos: "FWD", number: 20 },
  ],
  ENG: [
    { name: "J. Pickford", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "D. Henderson", pos: "GK", number: 13, isGoalkeeper: true },
    { name: "K. Walker", pos: "DEF", number: 2 },
    { name: "J. Stones", pos: "DEF", number: 5 },
    { name: "M. Guéhi", pos: "DEF", number: 6 },
    { name: "L. Shaw", pos: "DEF", number: 3 },
    { name: "T. Alexander-Arnold", pos: "DEF", number: 12 },
    { name: "D. Rice", pos: "MID", number: 4 },
    { name: "J. Bellingham", pos: "MID", number: 10 },
    { name: "K. Mainoo", pos: "MID", number: 26 },
    { name: "C. Gallagher", pos: "MID", number: 16 },
    { name: "H. Kane", pos: "FWD", number: 9, isCaptain: true },
    { name: "B. Saka", pos: "FWD", number: 7 },
    { name: "P. Foden", pos: "FWD", number: 11 },
    { name: "C. Palmer", pos: "FWD", number: 24 },
    { name: "O. Watkins", pos: "FWD", number: 18 },
  ],
  ESP: [
    { name: "U. Simón", pos: "GK", number: 23, isGoalkeeper: true },
    { name: "D. Raya", pos: "GK", number: 13, isGoalkeeper: true },
    { name: "D. Carvajal", pos: "DEF", number: 2 },
    { name: "R. Le Normand", pos: "DEF", number: 3 },
    { name: "A. Laporte", pos: "DEF", number: 14 },
    { name: "M. Cucurella", pos: "DEF", number: 24 },
    { name: "Rodri", pos: "MID", number: 16 },
    { name: "Pedri", pos: "MID", number: 8 },
    { name: "Fabián Ruiz", pos: "MID", number: 12 },
    { name: "Dani Olmo", pos: "MID", number: 10 },
    { name: "M. Merino", pos: "MID", number: 18 },
    { name: "N. Williams", pos: "FWD", number: 17 },
    { name: "Lamine Yamal", pos: "FWD", number: 19 },
    { name: "Á. Morata", pos: "FWD", number: 7, isCaptain: true },
    { name: "M. Oyarzabal", pos: "FWD", number: 21 },
    { name: "Ferran Torres", pos: "FWD", number: 11 },
  ],
  POR: [
    { name: "D. Costa", pos: "GK", number: 22, isGoalkeeper: true },
    { name: "R. Patrício", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "J. Cancelo", pos: "DEF", number: 20 },
    { name: "Rúben Dias", pos: "DEF", number: 3 },
    { name: "N. Mendes", pos: "DEF", number: 19 },
    { name: "Danilo Pereira", pos: "DEF", number: 13 },
    { name: "Rúben Neves", pos: "MID", number: 18 },
    { name: "J. Palhinha", pos: "MID", number: 6 },
    { name: "Bruno Fernandes", pos: "MID", number: 8 },
    { name: "Vitinha", pos: "MID", number: 16 },
    { name: "Bernardo Silva", pos: "MID", number: 10 },
    { name: "C. Ronaldo", pos: "FWD", number: 7, isCaptain: true },
    { name: "Rafael Leão", pos: "FWD", number: 15 },
    { name: "Diogo Jota", pos: "FWD", number: 21 },
    { name: "G. Ramos", pos: "FWD", number: 26 },
    { name: "João Félix", pos: "FWD", number: 11 },
  ],
  GER: [
    { name: "M. ter Stegen", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "O. Baumann", pos: "GK", number: 12, isGoalkeeper: true },
    { name: "J. Kimmich", pos: "DEF", number: 6 },
    { name: "A. Rüdiger", pos: "DEF", number: 2 },
    { name: "J. Tah", pos: "DEF", number: 4 },
    { name: "D. Raum", pos: "DEF", number: 3 },
    { name: "N. Schlotterbeck", pos: "DEF", number: 15 },
    { name: "R. Andrich", pos: "MID", number: 23 },
    { name: "İ. Gündoğan", pos: "MID", number: 21, isCaptain: true },
    { name: "J. Musiala", pos: "MID", number: 10 },
    { name: "F. Wirtz", pos: "MID", number: 17 },
    { name: "L. Sané", pos: "FWD", number: 19 },
    { name: "K. Havertz", pos: "FWD", number: 7 },
    { name: "N. Füllkrug", pos: "FWD", number: 9 },
    { name: "K. Adeyemi", pos: "FWD", number: 20 },
    { name: "D. Undav", pos: "FWD", number: 18 },
  ],
  NED: [
    { name: "B. Verbruggen", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "M. Flekken", pos: "GK", number: 12, isGoalkeeper: true },
    { name: "D. Dumfries", pos: "DEF", number: 22 },
    { name: "V. van Dijk", pos: "DEF", number: 4, isCaptain: true },
    { name: "S. de Vrij", pos: "DEF", number: 6 },
    { name: "N. Aké", pos: "DEF", number: 5 },
    { name: "M. de Ligt", pos: "DEF", number: 3 },
    { name: "F. de Jong", pos: "MID", number: 21 },
    { name: "T. Reijnders", pos: "MID", number: 14 },
    { name: "J. Veerman", pos: "MID", number: 15 },
    { name: "X. Simons", pos: "MID", number: 7 },
    { name: "C. Gakpo", pos: "FWD", number: 8 },
    { name: "M. Depay", pos: "FWD", number: 10 },
    { name: "D. Malen", pos: "FWD", number: 18 },
    { name: "W. Weghorst", pos: "FWD", number: 19 },
    { name: "B. Brobbey", pos: "FWD", number: 9 },
  ],
  USA: [
    { name: "M. Turner", pos: "GK", number: 1, isGoalkeeper: true },
    { name: "E. Steffen", pos: "GK", number: 12, isGoalkeeper: true },
    { name: "S. Dest", pos: "DEF", number: 2 },
    { name: "C. Richards", pos: "DEF", number: 3 },
    { name: "T. Ream", pos: "DEF", number: 13 },
    { name: "A. Robinson", pos: "DEF", number: 5 },
    { name: "J. Scally", pos: "DEF", number: 19 },
    { name: "T. Adams", pos: "MID", number: 4 },
    { name: "W. McKennie", pos: "MID", number: 8 },
    { name: "Y. Musah", pos: "MID", number: 6 },
    { name: "G. Reyna", pos: "MID", number: 7 },
    { name: "C. Pulisic", pos: "FWD", number: 10, isCaptain: true },
    { name: "T. Weah", pos: "FWD", number: 21 },
    { name: "F. Balogun", pos: "FWD", number: 20 },
    { name: "B. Aaronson", pos: "FWD", number: 11 },
    { name: "J. Sargent", pos: "FWD", number: 9 },
  ],
};
